game.AddAmmoType( { name = "SatCannon", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "40mmGrenade", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "C4Explosive", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "ProxMine", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "Improvised_Explosive", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "Nuclear_Warhead", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "NerveGas", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "StickyGrenade", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "Harpoon", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "nitroG", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "matador_rocket", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "m202_rocket", dmgtype = DMG_BLAST } )
game.AddAmmoType( { name = "rpg_rocket", dmgtype = DMG_BLAST } )

if CLIENT then
    language.Add( "40mmGrenade_ammo", "40mm Grenade" )
    language.Add( "C4Explosive_ammo", "C4" )
    language.Add( "ProxMine_ammo", "Proximity Mine" )
    language.Add( "Improvised_Explosive_ammo", "Improvised Explosive Device" )
    language.Add( "Nuclear_Warhead_ammo", "Nuclear Warhead" )
    language.Add( "NerveGas_ammo", "Nerve Gas" )
    language.Add( "StickyGrenade_ammo", "Sticky Grenade" )
    language.Add( "SatCannon_ammo", "Orbital Strike Cannon" )
    language.Add( "Harpoon_ammo", "Harpoon" )
    language.Add( "nitroG_ammo", "Nitro" )
    language.Add( "matador_rocket_ammo", "Matador Rocket" )
    language.Add( "m202_rocket_ammo", "M202 Rocket" )
    language.Add( "rpg_rocket_ammo", "RPG Rocket" )
end
