--AN-94
sound.Add( { name = "an94.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/an94/galil-1.wav" } )
sound.Add( { name = "an94.double", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/an94/doubletap.wav" } )
sound.Add( { name = "Weapon_an-94.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/an94/clipout.mp3" } )
sound.Add( { name = "Weapon_an-94.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/an94/clipin.mp3" } )
sound.Add( { name = "Weapon_an-94.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/an94/boltpull.mp3" } )
sound.Add( { name = "Weapon_an-94.Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/an94/draw.mp3" } )
--AMD65
sound.Add( { name = "amd65.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/amd65/amd-1.wav" } )
sound.Add( { name = "amd65.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/amd65/clipout.mp3" } )
sound.Add( { name = "amd65.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/amd65/magin2.mp3" } )
sound.Add( { name = "amd65.BoltPull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/amd65/boltpull.mp3" } )
sound.Add( { name = "amd65.BoltBack", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/amd65/boltrelease.mp3" } )
--tavor
sound.Add( { name = "Wep_imitavor.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/tavor/famas-1.wav" } )
sound.Add( { name = "Wep_imitavor.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tavor/famas_clipout.mp3" } )
sound.Add( { name = "Wep_imitavor.Clipout1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tavor/famas_clipout1.mp3" } )
sound.Add( { name = "Wep_imitavor.Tap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tavor/famas_tap.mp3" } )
sound.Add( { name = "Wep_imitavor.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tavor/famas_clipin.mp3" } )
sound.Add( { name = "Wep_imitavor.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tavor/famas_boltpull.mp3" } )
sound.Add( { name = "Wep_imitavor.Boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tavor/famas_boltrelease.mp3" } )
sound.Add( { name = "Wep_imitavor.Cloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tavor/famas_cloth.mp3" } )
--f2000
sound.Add( {
    name = "Weapon_F2000.Single",
    channel = CHAN_USER_BASE + 10,
    volume = 1.0,
    sound = { "weapons/fokku_tc_f2000/shot-1.wav", "weapons/fokku_tc_f2000/shot-2.wav", "weapons/fokku_tc_f2000/shot-3.wav", "weapons/fokku_tc_f2000/shot-4.wav" }
} )
sound.Add( { name = "f2000.playerbreathing", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_f2000/playerbreathing.mp3" } )
sound.Add( { name = "f2000.lightcloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_f2000/cloth2.mp3" } )
sound.Add( { name = "f2000.heavycloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_f2000/cloth.mp3" } )
sound.Add( { name = "f2000.magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_f2000/clipout.mp3" } )
sound.Add( { name = "f2000.magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_f2000/clipin.mp3" } )
sound.Add( { name = "f2000.boltback", channel = CHAN_ITEM, volume = 1.0, sound = { "weapons/fokku_tc_f2000/chargeback.mp3", "weapons/fokku_tc_f2000/chargeback1.mp3" } } )
sound.Add( { name = "f2000.boltforward", channel = CHAN_ITEM, volume = 1.0, sound = { "weapons/fokku_tc_f2000/chargefor.mp3", "weapons/fokku_tc_f2000/chargefor1.mp3" } } )
--ak-47
sound.Add( { name = "47ak.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/AYKAYFORTY/ak47-1.wav" } )
sound.Add( { name = "47ak.Bolt", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/AYKAYFORTY/bolt.mp3" } )
sound.Add( { name = "47ak.magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/AYKAYFORTY/magin.mp3" } )
sound.Add( { name = "47ak.magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/AYKAYFORTY/magout.mp3" } )
--m14
sound.Add( { name = "Weapon_M14SP.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/fokku_tc_m14/sg550-1.wav" } )
sound.Add( { name = "Weapon_M14SP.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_m14/sg550_clipout.mp3" } )
sound.Add( { name = "Weapon_M14SP.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_m14/sg550_clipin.mp3" } )
sound.Add( { name = "Weapon_M14SP.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_m14/sg550_boltpull.mp3" } )
sound.Add( { name = "Weapon_M14.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_m14/sg550_deploy.mp3" } )
--g36
sound.Add( { name = "G36.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/G36/m4a1_unsil-1.wav" } )
sound.Add( { name = "G36.Boltback", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/Boltback.mp3" } )
sound.Add( { name = "G36.BoltPull", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/BoltPull.mp3" } )
sound.Add( { name = "G36.Cloth", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/Cloth.mp3" } )
sound.Add( { name = "G36.PocketRussle", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/PocketRussle.mp3" } )
sound.Add( { name = "G36.MagOut", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/MagOut.mp3" } )
sound.Add( { name = "G36.MagFiddle", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/MagFiddle.mp3" } )
sound.Add( { name = "G36.MagSlap", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/MagSlap.mp3" } )
sound.Add( { name = "G36.PlaceSilencer", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/PlaceSilencer.mp3" } )
sound.Add( { name = "G36.TightenSilencer", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/TightenSilencer.mp3" } )
sound.Add( { name = "G36.SpinSilencer", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/SpinSilencer.mp3" } )
sound.Add( { name = "G36.Safety", channel = CHAN_ITEM, volume = 1, sound = "weapons/G36/Safety.mp3" } )
--winchester1873
sound.Add( { name = "Weapon_73.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/winchester73/w73-1.wav" } )
sound.Add( { name = "Weapon_73.Pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/winchester73/w73pump.mp3" } )
sound.Add( { name = "Weapon_73.Insertshell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/winchester73/w73insertshell.mp3" } )
--l85
sound.Add( { name = "Weapon_l85.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/L85A2/aug-1.wav" } )
sound.Add( { name = "Weapon_l85.magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/L85A2/magin.mp3" } )
sound.Add( { name = "Weapon_l85.magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/L85A2/magout.mp3" } )
sound.Add( { name = "Weapon_l85.boltslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/L85A2/boltslap.mp3" } )
sound.Add( { name = "Weapon_l85.boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/L85A2/boltpull.mp3" } )
sound.Add( { name = "Weapon_l85.cloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/L85A2/cloth.mp3" } )
sound.Add( { name = "Weapon_l85.Tap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/L85A2/tap.mp3" } )
--auga3
sound.Add( { name = "aug_a3.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = { "weapons/auga3/aug-1.wav", "weapons/auga3/aug-2.wav" } } )
sound.Add( { name = "Weap_auga3.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/auga3/clipout.mp3" } )
sound.Add( { name = "Weap_auga3.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/auga3/clipin.mp3" } )
sound.Add( { name = "Weap_auga3.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/auga3/boltpull.mp3" } )
sound.Add( { name = "Weap_auga3.boltslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/auga3/boltslap.mp3" } )
--famas
sound.Add( { name = "Weapon_FAMTC.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = { "weapons/fokku_tc_famas/shot-1.wav", "weapons/fokku_tc_famas/shot-2.wav" } } )
sound.Add( { name = "Weapon_FAMTC.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_famas/famas_clipout.mp3" } )
sound.Add( { name = "Weapon_FAMTC.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_famas/famas_clipin.mp3" } )
sound.Add( { name = "Weapon_FAMTC.forearm", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_famas/famas_forearm.mp3" } )
--Val
sound.Add( { name = "Dmgfok_vally.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dmg_val/galil-1.wav" } )
sound.Add( { name = "Dmgfok_vally.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_val/galil_clipout.mp3" } )
sound.Add( { name = "Dmgfok_vally.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_val/galil_clipin.mp3" } )
sound.Add( { name = "Dmgfok_vally.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_val/galil_Boltpull.mp3" } )
sound.Add( { name = "Dmgfok_vally.Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_val/draw.mp3" } )
--vikhr
sound.Add( { name = "Dmgfok_vikhr.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dmg_vikhr/galil-1.wav" } )
sound.Add( { name = "Dmgfok_vikhr.Silenced", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_vikhr/galil-sil.mp3" } )
sound.Add( { name = "Dmgfok_vikhr.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_vikhr/galil_clipout.mp3" } )
sound.Add( { name = "Dmgfok_vikhr.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_vikhr/galil_clipin.mp3" } )
sound.Add( { name = "Dmgfok_vikhr.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_vikhr/galil_Boltpull.mp3" } )
sound.Add( { name = "Dmgfok_vikhr.Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_vikhr/draw.mp3" } )
--magpulmasadaACR
sound.Add( { name = "Masada.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = ")weapons/masadamagpul/masada_unsil.wav" } )
sound.Add( { name = "Masada.Cloth1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/cloth1.mp3" } )
sound.Add( { name = "Masada.Cloth2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/cloth2.mp3" } )
sound.Add( { name = "Masada.Magin1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/magin1.mp3" } )
sound.Add( { name = "Masada.Magin2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/magin2.mp3" } )
sound.Add( { name = "Masada.Foley", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/foley.mp3" } )
sound.Add( { name = "Masada.Magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/magout.mp3" } )
sound.Add( { name = "Masada.Magslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/magslap.mp3" } )
sound.Add( { name = "Masada.Safety", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/safety.mp3" } )
sound.Add( { name = "Masada.Chargerback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/chargerback.mp3" } )
sound.Add( { name = "Masada.Boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/boltrelease.mp3" } )
sound.Add( { name = "Masada.Placesilencer", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/placesilencer.mp3" } )
sound.Add( { name = "Masada.Removesilencer", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/masadamagpul/removesilencer.mp3" } )
--m4a1
sound.Add( { name = "Dmgfok_M4A1.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_unsil-1.wav" } )
sound.Add( { name = "Dmgfok_M4A1.Silencer_Off", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_silencer_off.mp3" } )
sound.Add( { name = "Dmgfok_M4A1.Silencer_On", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_silencer_on.mp3" } )
sound.Add( { name = "Dmgfok_M4A1.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_clipout.mp3" } )
sound.Add( { name = "Dmgfok_M4A1.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_clipin.mp3" } )
sound.Add( { name = "Dmgfok_M4A1.Boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_boltrelease.mp3" } )
sound.Add( { name = "Dmgfok_M4A1.Boltrelease2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_boltrelease_silenced.mp3" } )
sound.Add( { name = "Dmgfok_M4A1.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m4a1/m4a1_boltpull.mp3" } )
--m16a4
sound.Add( { name = "Dmgfok_M16A4.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = ")weapons/dmg_m16a4/shoot.wav" } )
sound.Add( { name = "Dmgfok_M16A4.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m16a4/magout.mp3" } )
sound.Add( { name = "Dmgfok_M16A4.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m16a4/magin.mp3" } )
sound.Add( { name = "Dmgfok_M16A4.Boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m16a4/boltrelease.mp3" } )
sound.Add( { name = "Dmgfok_M16A4.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m16a4/boltpull.mp3" } )
--Congratulations, youhavefoundasecretmessage!Bobsayshi, andhopesyouarehavingfunwiththisaddon.
--ak47
sound.Add( { name = "Tactic_AK47.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/fokku_tc_ak47/ak47-1.wav" } )
sound.Add( { name = "Tactic_AK47.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_ak47/ak47_clipout.mp3" } )
sound.Add( { name = "Tactic_AK47.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_ak47/ak47_clipin.mp3" } )
sound.Add( { name = "Tactic_AK47.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_ak47/ak47_boltpull.mp3" } )
--SCAR
sound.Add( { name = "Wep_fnscarh.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = { "weapons/fnscarh/aug-1.wav", "weapons/fnscarh/aug-2.wav", "weapons/fnscarh/aug-3.wav" } } )
sound.Add( { name = "Wep_fnscar.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fnscarh/aug_boltpull.mp3" } )
sound.Add( { name = "Wep_fnscar.Boltslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fnscarh/aug_boltslap.mp3" } )
sound.Add( { name = "Wep_fnscar.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fnscarh/aug_clipout.mp3" } )
sound.Add( { name = "Wep_fnscar.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fnscarh/aug_clipin.mp3" } )
--fnfal
sound.Add( { name = "fnfal.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/fn_fal/galil-1.wav" } )
sound.Add( { name = "Weapon_fnfal.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fn_fal/galil_clipout.mp3" } )
sound.Add( { name = "Weapon_fnfal.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fn_fal/galil_clipin.mp3" } )
sound.Add( { name = "Weapon_fnfal.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fn_fal/galil_boltpull.mp3" } )
--hk416
sound.Add( { name = "hk416weapon.SilencedSingle", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1-1.wav" } )
sound.Add( { name = "hk416weapon.UnsilSingle", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_unsil-1.wav" } )
sound.Add( { name = "hk416weapon.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_clipout.mp3" } )
sound.Add( { name = "hk416weapon.Magtap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_tap.mp3" } )
sound.Add( { name = "hk416weapon.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_clipin.mp3" } )
sound.Add( { name = "hk416weapon.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_boltpull.mp3" } )
sound.Add( { name = "hk416weapon.Boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_boltrelease.mp3" } )
sound.Add( { name = "hk416weapon.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_deploy.mp3" } )
sound.Add( { name = "hk416weapon.Silencer_On", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_silencer_on.mp3" } )
sound.Add( { name = "hk416weapon.Silencer_Off", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/twinkie_hk416/m4a1_silencer_off.mp3" } )
--G3
sound.Add( { name = "hk_g3_weapon.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/hk_g3/galil-1.wav" } )
sound.Add( { name = "hk_g3_weapon.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_g3/galil_clipout.mp3" } )
sound.Add( { name = "hk_g3_weapon.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_g3/galil_clipin.mp3" } )
sound.Add( { name = "hk_g3_weapon.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_g3/boltpull.mp3" } )
sound.Add( { name = "hk_g3_weapon.Boltforward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_g3/boltforward.mp3" } )
sound.Add( { name = "hk_g3_weapon.cloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_g3/Cloth.mp3" } )
sound.Add( { name = "hk_g3_weapon.draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_g3/draw.mp3" } )
--PKM
sound.Add( {
    name = "pkm.single",
    channel = CHAN_USER_BASE + 10,
    volume = 1.0,
    sound = { "weapons/pkm/pkm-1.wav", "weapons/pkm/pkm-2.wav", "weapons/pkm/pkm-3.wav", "weapons/pkm/pkm-4.wav", "weapons/pkm/pkm-5.wav" }
} )
sound.Add( { name = "Weapon_PKM.Cloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_cloth.mp3" } )
sound.Add( { name = "Weapon_PKM.Coverup", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_coverup.mp3" } )
sound.Add( { name = "Weapon_PKM.Bullet", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_bullet.mp3" } )
sound.Add( { name = "Weapon_PKM.Boxout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_boxout.mp3" } )
sound.Add( { name = "Weapon_PKM.Boxin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_boxin.mp3" } )
sound.Add( { name = "Weapon_PKM.Chain", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_chain.mp3" } )
sound.Add( { name = "Weapon_PKM.Coverdown", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_coverdown.mp3" } )
sound.Add( { name = "Weapon_PKM.Coversmack", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_coversmack.mp3" } )
sound.Add( { name = "Weapon_PKM.Bolt", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_bolt.mp3" } )
sound.Add( { name = "Weapon_PKM.Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pkm/pkm_draw.mp3" } )
--SVT40
sound.Add( { name = "Weapon_SVT40.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/svt40/g3sg1-1.wav" } )
sound.Add( { name = "Weapon_SVT40.Cloth1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svt40/g3sg1_cloth1.mp3" } )
sound.Add( { name = "Weapon_SVT40.Cloth2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svt40/g3sg1_cloth2.mp3" } )
sound.Add( { name = "Weapon_SVT40.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svt40/g3sg1_clipout.mp3" } )
sound.Add( { name = "Weapon_SVT40.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svt40/g3sg1_clipin.mp3" } )
sound.Add( { name = "Weapon_SVT40.ClipTap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svt40/g3sg1_cliptap.mp3" } )
sound.Add( { name = "Weapon_SVT40.SlideBack", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svt40/g3sg1_slide_b.mp3" } )
sound.Add( { name = "Weapon_SVT40.SlideForward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svt40/g3sg1_slide_f.mp3" } )
--spas12
sound.Add( { name = "spas_12_shoty.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/spas_12/xm1014-1.wav" } )
sound.Add( { name = "spas_12_shoty.insert", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/spas_12/xm_insert.mp3" } )
sound.Add( { name = "spas_12_shoty.cock", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/spas_12/xm_cock.mp3" } )
--USAS
sound.Add( { name = "Weapon_usas.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/usas12/xm1014-1.wav" } )
sound.Add( { name = "Weapon_usas.clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/usas12/magin.mp3" } )
sound.Add( { name = "Weapon_usas.clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/usas12/magout.mp3" } )
sound.Add( { name = "Weapon_usas.draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/usas12/draw.mp3" } )
--remington7615P
sound.Add( { name = "7615p_remington.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/7615p/scout_fire-1.wav" } )
sound.Add( { name = "7615p_bob.pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/7615p/m3_pump.mp3" } )
sound.Add( { name = "Weapon_7615P.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/7615p/sg550_clipout.mp3" } )
sound.Add( { name = "Weapon_7615P.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/7615p/sg550_clipin.mp3" } )
--DragunovSVU
sound.Add( { name = "Weapon_SVU.Single", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svu/g3sg1-1.wav" } )
sound.Add( { name = "Weapon_svuxx.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svu/g3sg1_clipin.mp3" } )
sound.Add( { name = "Weapon_svuxx.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svu/g3sg1_clipout.mp3" } )
sound.Add( { name = "Weapon_svuxx.Slide", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/svu/g3sg1_slide.mp3" } )
--Winchestermodel94
sound.Add( { name = "Weapon_Win94.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/win94/scout_fire-1.wav" } )
sound.Add( { name = "Weapon_Win94.Bolt", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/win94/scout_bolt.mp3" } )
sound.Add( { name = "weapons/hamburgpling.wav", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/win94/hamburgpling.mp3" } )
sound.Add( { name = "Weapon_Win94.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/win94/scout_clipout.mp3" } )
--Striker12
sound.Add( { name = "ShotStriker12.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/striker12/xm1014-1.wav" } )
sound.Add( { name = "ShotStriker12.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/striker12/deploy.mp3" } )
sound.Add( { name = "ShotStriker12.InsertShell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/striker12/m3_insertshell.mp3" } )
--AW50
sound.Add( { name = "Weaponaw50.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/aw50/awp_fire.wav" } )
sound.Add( { name = "Weaponaw50.clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/aw50/awp_magin.mp3" } )
sound.Add( { name = "Weaponaw50.clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/aw50/awp_magout.mp3" } )
sound.Add( { name = "Weaponaw50.boltback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/aw50/m24_boltback.mp3" } )
sound.Add( { name = "Weaponaw50.boltforward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/aw50/m24_boltforward.mp3" } )
--PSG-1
sound.Add( { name = "Weapon_psg_1.Single", channel = CHAN_USER_BASE + 10, volume = 1, sound = "weapons/psg1/g3sg1-1.wav" } )
sound.Add( { name = "Weapon_psg_1.Back", channel = CHAN_ITEM, volume = 1, sound = "weapons/psg1/psg_boltpull.mp3" } )
sound.Add( { name = "Weapon_psg_1.Clipout", channel = CHAN_ITEM, volume = 1, sound = "weapons/psg1/psg_clipout.mp3" } )
sound.Add( { name = "Weapon_psg_1.Clipin", channel = CHAN_ITEM, volume = 1, sound = "weapons/psg1/psg_clipin.mp3" } )
sound.Add( { name = "Weapon_psg_1.Forward", channel = CHAN_ITEM, volume = 1, sound = "weapons/psg1/psg_boltrelease.mp3" } )
sound.Add( { name = "Weapon_psg_1.Deploy", channel = CHAN_ITEM, volume = 1, sound = "weapons/psg1/deploy1.mp3" } )
--contender
sound.Add( {
    name = "contender_g2.Single",
    channel = CHAN_USER_BASE + 10,
    volumel = 1.0,
    sound = { "weapons/g2contender/scout-1.wav", "weapons/g2contender/scout-2.wav", "weapons/g2contender/scout-3.wav" }
} )
sound.Add( { name = "contender_g2.Draw", channel = CHAN_ITEM, volumel = 1.0, sound = "weapons/g2contender/Draw.mp3" } )
sound.Add( { name = "contender_g2.Hammer", channel = CHAN_USER_BASE + 1, volumel = 1.0, sound = { "weapons/g2contender/Cock-1.mp3", "weapons/g2contender/Cock-2.mp3" } } )
sound.Add( { name = "contender_g2.Open", channel = CHAN_ITEM, volumel = 1.0, sound = "weapons/g2contender/open_chamber.mp3" } )
sound.Add( { name = "contender_g2.Shellout", channel = CHAN_USER_BASE + 1, volumel = 1.0, sound = "weapons/g2contender/Bullet_out.mp3" } )
sound.Add( { name = "contender_g2.Shellin", channel = CHAN_ITEM, volumel = 1.0, sound = "weapons/g2contender/Bullet_in.mp3" } )
sound.Add( { name = "contender_g2.Close", channel = CHAN_ITEM, volumel = 1.0, sound = "weapons/g2contender/close_chamber.mp3" } )
sound.Add( {
    name = "contender_g2.Shell",
    channel = CHAN_USER_BASE + 2,
    volumel = 1.0,
    sound = { "weapons/g2contender/pl_shell1.mp3", "weapons/g2contender/pl_shell2.mp3", "weapons/g2contender/pl_shell3.mp3", "weapons/g2contender/pl_shell4.mp3" }
} )
--BarretM98B
sound.Add( { name = "M98.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/M98/shot-1.wav" } )
sound.Add( { name = "M98_Bolt", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/bolt.mp3" } )
sound.Add( { name = "M98_Handle", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/handle.mp3" } )
sound.Add( { name = "M98_Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/draw.mp3" } )
sound.Add( { name = "M98_Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/draw_2.mp3" } )
sound.Add( { name = "M98_Foley", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/foley.mp3" } )
sound.Add( { name = "M98_Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/clipout.mp3" } )
sound.Add( { name = "M98_Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/clipin.mp3" } )
sound.Add( { name = "M98_Boltback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/boltback.mp3" } )
sound.Add( { name = "M98_Boltforward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M98/boltforward.mp3" } )
--barretm8250cal
sound.Add( { name = "BarretM82.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/M82/barret50-1.wav" } )
sound.Add( { name = "Weapon_M82.Boltup", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M82/boltup.mp3" } )
sound.Add( { name = "Weapon_M82.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M82/clipin.mp3" } )
sound.Add( { name = "Weapon_M82.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M82/clipout.mp3" } )
sound.Add( { name = "Weapon_M82.Boltdown", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M82/boltdown.mp3" } )
--m24
sound.Add( { name = "Dmgfok_M24SN.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dmg_m24/awp1.wav" } )
sound.Add( { name = "Dmgfok_M24SN.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m24/m24_magin.mp3" } )
sound.Add( { name = "Dmgfok_M24SN.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m24/m24_magout.mp3" } )
sound.Add( { name = "Dmgfok_M24SN.Boltback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m24/m24_boltback.mp3" } )
sound.Add( { name = "Dmgfok_M24SN.Boltforward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_m24/m24_boltforward.mp3" } )
--svddragunov
sound.Add( { name = "Weapon_svd01.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/SVD/g3sg1-1.wav" } )
sound.Add( { name = "Weapon_SVD.Foley", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/foley.mp3" } )
sound.Add( { name = "Weapon_SVD.Handle", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/handle.mp3" } )
sound.Add( { name = "Weapon_SVD.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/Clipout.mp3" } )
sound.Add( { name = "Weapon_SVD.Cliptap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/Cliptap.mp3" } )
sound.Add( { name = "Weapon_SVD.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/ClipIn.mp3" } )
sound.Add( { name = "Weapon_SVD.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/SlideBack.mp3" } )
sound.Add( { name = "Weapon_SVD.SlideForward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/SlideForward.mp3" } )
sound.Add( { name = "Weapon_SVD.Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/SVD/Draw.mp3" } )
--sl8
sound.Add( {
    name = "Weapon_hksl8.Single",
    channel = CHAN_USER_BASE + 10,
    volume = 1.0,
    sound = { "weapons/hksl8/SG552-1.wav", "weapons/hksl8/SG552-2.wav", "weapons/hksl8/SG552-3.wav", "weapons/hksl8/SG552-4.wav" }
} )
sound.Add( { name = "sl8.Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hksl8/draw.mp3" } )
sound.Add( { name = "sl8.Safety", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hksl8/safety.mp3" } )
sound.Add( { name = "sl8.Magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hksl8/magout.mp3" } )
sound.Add( { name = "sl8.MagFiddle", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hksl8/magfiddle.mp3" } )
sound.Add( { name = "sl8.MagIn", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hksl8/magin.mp3" } )
sound.Add( { name = "sl8.BoltBack", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hksl8/boltback.mp3" } )
sound.Add( { name = "sl8.Boltforward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hksl8/boltforward.mp3" } )
--intervention
sound.Add( { name = "Weapon_INT.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/fokku_tc_intrv/int1.wav" } )
sound.Add( { name = "Weapon_INT.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_intrv/int_deploy.mp3" } )
sound.Add( { name = "Weapon_INT.Bolt", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_intrv/int_bolt.mp3" } )
sound.Add( { name = "Weapon_INT.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_intrv/int_clipout.mp3" } )
sound.Add( { name = "Weapon_INT.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_intrv/int_clipin.mp3" } )
--winchester1887
sound.Add( { name = "1887winch.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/1887winchester/1887-1.wav" } )
sound.Add( { name = "1887winch.Insertshell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/1887winchester/1887_insertshell.mp3" } )
sound.Add( { name = "1887winch.Pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/1887winchester/1887pump1.mp3" } )
sound.Add( { name = "1887pump2.Pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/1887winchester/1887pump2.mp3" } )
--winchester1897
sound.Add( { name = "Trench_97.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/1897trench/m3-1.wav" } )
sound.Add( { name = "Trench_97.Insertshell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/1897trench/m3_insertshell.mp3" } )
sound.Add( { name = "Trench_97.Pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/1897trench/m3_pump.mp3" } )
sound.Add( { name = "Trench_07.Pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/1897trench/1897_deploy.mp3" } )
--browningauto5
sound.Add( { name = "Weapon_a5.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/browninga5/xm1014-1.wav" } )
sound.Add( { name = "Weapon_bauto5.InsertShell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/browninga5/xm1014_insertshell.mp3" } )
sound.Add( { name = "Weapon_a5.back", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/browninga5/xm1014_check.mp3" } )
sound.Add( { name = "Weapon_a5.draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/browninga5/xm1014_deploy.mp3" } )
--doublebarrelshotgun
sound.Add( { name = "Double_Barrel.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dbarrel/xm1014-1.wav" } )
sound.Add( { name = "dbarrel_dblast", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dbarrel/dblast.wav" } )
sound.Add( { name = "Double_Barrel.InsertShell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dbarrel/xm1014_insertshell.mp3" } )
sound.Add( { name = "Double_Barrel.barreldown", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dbarrel/barreldown.mp3" } )
sound.Add( { name = "Double_Barrel.barrelup", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dbarrel/barrelup.mp3" } )
--pancorjackhammer
sound.Add( { name = "Weapon_Jackhammer.Single", channel = CHAN_USER_BASE + 10, volume = .65, sound = "weapons/jackhammer/xm1014-1.wav" } )
sound.Add( { name = "Weapon_Jackhammer.Clipout", channel = CHAN_ITEM, volume = .65, sound = "weapons/jackhammer/clipout.mp3" } )
sound.Add( { name = "Weapon_Jackhammer.Clipin", channel = CHAN_ITEM, volume = .65, sound = "weapons/jackhammer/magtap.mp3" } )
sound.Add( { name = "Weapon_Jackhammer.Forearm", channel = CHAN_ITEM, volume = .45, sound = "weapons/jackhammer/boltcatch.mp3" } )
sound.Add( { name = "Weapon_Jackhammer.Cloth", channel = CHAN_ITEM, volume = 1, sound = "weapons/jackhammer/cloth.mp3" } )
--IthacaM37
sound.Add( { name = "IthacaM37.Single", channel = CHAN_USER_BASE + 10, volume = 1, sound = "weapons/m37/m3-1.wav" } )
sound.Add( { name = "IthacaM37.Insertshell", channel = CHAN_ITEM, volume = 1, sound = "weapons/m37/m3_insertshell.mp3" } )
sound.Add( { name = "IthacaM37.Pump", channel = CHAN_ITEM, volume = 1, sound = "weapons/m37/m3_pump.mp3" } )
--Mossberg590
sound.Add( { name = "Mberg_590.Single", channel = CHAN_USER_BASE + 10, volume = 1, sound = "weapons/590/m3-1.wav" } )
sound.Add( { name = "Mberg_590.Insertshell", channel = CHAN_ITEM, volume = 1, sound = "weapons/590/m3_insertshell.mp3" } )
sound.Add( { name = "Mberg_590.Pump", channel = CHAN_ITEM, volume = 1, sound = "weapons/590/m3_pump.mp3" } )
sound.Add( { name = "Mberg_590.Bullet", channel = CHAN_ITEM, volume = 1, sound = "weapons/590/m3_bullet.mp3" } )
sound.Add( { name = "Mberg_590.Draw", channel = CHAN_ITEM, volume = 1, sound = "weapons/590/m3_draw.mp3" } )
--AresShrike
sound.Add( { name = "Weapon_shrk.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/shrike/shrike-1.wav" } )
sound.Add( { name = "Weapon_shrk.bOut", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/boxout.mp3" } )
sound.Add( { name = "Weapon_shrk.Button", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/button.mp3" } )
sound.Add( { name = "Weapon_shrk.cUp", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/coverup.mp3" } )
sound.Add( { name = "Weapon_shrk.Bullet1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/bullet.mp3" } )
sound.Add( { name = "Weapon_shrk.bIn", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/boxin.mp3" } )
sound.Add( { name = "Weapon_shrk.Bullet2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/bullet.mp3" } )
sound.Add( { name = "Weapon_shrk.cDown", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/coverdown.mp3" } )
sound.Add( { name = "Weapon_shrk.Ready", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/shrike/ready.mp3" } )
--m60
sound.Add( { name = "Weapon_M_60.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = ")weapons/m60/m60-1.wav" } )
sound.Add( { name = "Weapon_M_60.Coverup", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/m60/m60_coverup.mp3" } )
sound.Add( { name = "Weapon_M_60.Boxout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/m60/m60_boxout.mp3" } )
sound.Add( { name = "Weapon_M_60.Boxin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/m60/m60_boxin.mp3" } )
sound.Add( { name = "Weapon_M_60.Chain", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/m60/m60_chain.mp3" } )
sound.Add( { name = "Weapon_M_60.Coverdown", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/m60/m60_coverdown.mp3" } )
--m249
sound.Add( { name = "Weapon_249M.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/schmung.M249/m249-1.wav" } )
sound.Add( { name = "Weapon_249M.Coverdown", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/schmung.M249/m249_coverdown.mp3" } )
sound.Add( { name = "Weapon_249M.Chain", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/schmung.M249/m249_chain.mp3" } )
sound.Add( { name = "Weapon_249M.Coverup", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/schmung.M249/m249_coverup.mp3" } )
sound.Add( { name = "Weapon_249M.Boxout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/schmung.M249/m249_boxout.mp3" } )
sound.Add( { name = "Weapon_Flakk249.Magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/schmung.M249/magin.mp3" } )
sound.Add( { name = "Weapon_Flakk249.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/schmung.M249/boltpull.mp3" } )
sound.Add( { name = "Weapon_Flakk249.Boltrel", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/schmung.M249/boltrel.mp3" } )
--m134minigun
sound.Add( { name = "BlackVulcan.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = ")weapons/minigun/mini-1.wav" } )
sound.Add( { name = "BlackVulcan.Boxout", channel = CHAN_ITEM, volume = 1.0, sound = ")weapons/minigun/mini_boxout.mp3" } )
sound.Add( { name = "BlackVulcan.Coverup", channel = CHAN_ITEM, volume = 1.0, sound = ")weapons/minigun/mini_coverup.mp3" } )
sound.Add( { name = "BlackVulcan.Boxin", channel = CHAN_ITEM, volume = 1.0, sound = ")weapons/minigun/mini_boxin.mp3" } )
sound.Add( { name = "BlackVulcan.Chain", channel = CHAN_ITEM, volume = 1.0, sound = ")weapons/minigun/mini_chain.mp3" } )
sound.Add( { name = "BlackVulcan.Coverdown", channel = CHAN_ITEM, volume = 1.0, sound = ")weapons/minigun/mini_coverdown.mp3" } )
--fg42
sound.Add( { name = "FG42_weapon.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/fg42/ak47-1.wav" } )
sound.Add( { name = "FG42_weapon.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fg42/ak47_clipout.mp3" } )
sound.Add( { name = "FG42_weapon.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fg42/ak47_clipin.mp3" } )
sound.Add( { name = "FG42_weapon.BoltPull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fg42/ak47_boltpull.mp3" } )
--m1918bar
sound.Add( { name = "Weapon_bar1.clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/jen.ak/mag.in.mp3" } )
sound.Add( { name = "Weapon_bar1.clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/jen.ak/mag.out.mp3" } )
sound.Add( { name = "Weapon_bar1.mag.tap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/jen.ak/mag.tap.mp3" } )
sound.Add( { name = "Weapon_bar1.boltpull", channel = CHAN_ITEM, volume = .7, sound = "weapons/jen.ak/bolt.pull.mp3" } )
sound.Add( { name = "Weapon_bar1.bolt.rel", channel = CHAN_ITEM, volume = .5, sound = "weapons/jen.ak/bolt.rel.mp3" } )
sound.Add( { name = "Weapon_bar1.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/jen.ak/fire.wav" } )
sound.Add( { name = "3rd_Weapon_bar1.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/jen.ak/fire.wav" } )
--Tactical870
sound.Add( { name = "WepRem870.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/tact870/m3-1.wav" } )
sound.Add( { name = "WepRem870.pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tact870/m3_pump.mp3" } )
sound.Add( { name = "WepRem870.Insertshell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tact870/m3_insertshell.mp3" } )
--BenelliM3
sound.Add( { name = "BenelliM3.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/BenelliM3/m3-1.wav" } )
sound.Add( { name = "BenelliM3.insertshell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/BenelliM3/m3_insertshell.mp3" } )
sound.Add( { name = "BenelliM3.Pump", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/BenelliM3/m3_pump.mp3" } )
--MP40
sound.Add( { name = "mp40.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/mp40/mp5-1.wav" } )
sound.Add( { name = "Weapon_mp40m9k.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp40/magout.mp3" } )
sound.Add( { name = "Weapon_mp40m9k.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp40/magin.mp3" } )
sound.Add( { name = "Weapon_mp40m9k.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp40/boltback.mp3" } )
--MagpulPDR
sound.Add( { name = "MAG_PDR.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = { "weapons/pdr/pdr-1.wav", "weapons/pdr/pdr-2.wav", "weapons/pdr/pdr-3.wav" } } )
sound.Add( { name = "Weapon_PDR.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pdr/pdr_clipin.mp3" } )
sound.Add( { name = "Weapon_PDR.Clipin2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pdr/pdr_clipin2.mp3" } )
sound.Add( { name = "Weapon_PDR.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pdr/pdr_boltpull.mp3" } )
sound.Add( { name = "Weapon_PDR.Boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pdr/pdr_boltrelease.mp3" } )
sound.Add( { name = "Weapon_PDR.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/pdr/pdr_clipout.mp3" } )
--KACPDW
sound.Add( { name = "KAC_PDW.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/kac_pdw/m4a1_unsil-1.wav" } )
sound.Add( { name = "KAC_PDW.SilentSingle", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/kac_pdw/m4a1-1.wav" } )
sound.Add( { name = "kac_pdw_001.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/kac_pdw/m4a1_clipout.mp3" } )
sound.Add( { name = "kac_pdw_001.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/kac_pdw/m4a1_clipin.mp3" } )
sound.Add( { name = "kac_pdw_001.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/kac_pdw/m4a1_boltpull.mp3" } )
sound.Add( { name = "kac_pdw_001.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/kac_pdw/m4a1_deploy.mp3" } )
sound.Add( { name = "kac_pdw_001.Silencer_On", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/kac_pdw/m4a1_silencer_on.mp3" } )
sound.Add( { name = "kac_pdw_001.Silencer_Off", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/kac_pdw/m4a1_silencer_off.mp3" } )
--MP5
sound.Add( { name = "mp5_navy_Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/brightmp5/mp5-1.wav" } )
sound.Add( { name = "mp5_foley", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/foley.mp3" } )
sound.Add( { name = "mp5_magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/magout.mp3" } )
sound.Add( { name = "mp5_magin1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/magin1.mp3" } )
sound.Add( { name = "mp5_magin2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/magin2.mp3" } )
sound.Add( { name = "mp5_boltback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/boltback.mp3" } )
sound.Add( { name = "mp5_boltslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/boltslap.mp3" } )
sound.Add( { name = "mp5_cloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/cloth.mp3" } )
sound.Add( { name = "mp5_safety", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/brightmp5/safety.mp3" } )
--tec9
sound.Add( { name = "Weapon_Tec9.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/tec9/ump45-1.wav" } )
sound.Add( { name = "Weapon_Tec9.Magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tec9/tec9_magin.mp3" } )
sound.Add( { name = "Weapon_Tec9.Magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tec9/tec9_magout.mp3" } )
sound.Add( { name = "Weapon_Tec9.NewMag", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tec9/tec9_newmag.mp3" } )
sound.Add( { name = "Weapon_Tec9.Charge", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tec9/tec9_charge.mp3" } )
--Kriss
sound.Add( { name = "kriss_vector.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/Kriss/ump45-1.wav" } )
sound.Add( { name = "kriss_vector.Magrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/Kriss/magrel.mp3" } )
sound.Add( { name = "kriss_vector.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/Kriss/clipout.mp3" } )
sound.Add( { name = "kriss_vector.Dropclip", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/Kriss/dropclip.mp3" } )
sound.Add( { name = "kriss_vector.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/Kriss/clipin.mp3" } )
sound.Add( { name = "kriss_vector.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/Kriss/boltpull.mp3" } )
sound.Add( { name = "kriss_vector.unfold", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/Kriss/unfold.mp3" } )
--MP9
sound.Add( { name = "Weapon_mp9.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/mp9/tmp-1.wav" } )
sound.Add( { name = "Weapon_mp9.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp9/tmp_clipin.mp3" } )
sound.Add( { name = "Weapon_mp9.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp9/tmp_clipout.mp3" } )
--ump45
sound.Add( { name = "m9k_hk_ump45.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/hk_ump45/ump45-1.wav" } )
sound.Add( { name = "m9k_hk_ump45.Clipout1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_ump45/ump45_clipout1.mp3" } )
sound.Add( { name = "m9k_hk_ump45.Clipout2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_ump45/ump45_clipout2.mp3" } )
sound.Add( { name = "m9k_hk_ump45.Clipin1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_ump45/ump45_clipin1.mp3" } )
sound.Add( { name = "m9k_hk_ump45.Clipin2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_ump45/ump45_clipin2.mp3" } )
sound.Add( { name = "m9k_hk_ump45.Boltslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_ump45/ump45_boltslap.mp3" } )
sound.Add( { name = "m9k_hk_ump45.Cloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hk_ump45/ump45_cloth.mp3" } )
--p19Bizon
sound.Add( { name = "Weapon_P19.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/p19/p90-1.wav" } )
sound.Add( { name = "Weapon_P19.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/p19/p90_clipout.mp3" } )
sound.Add( { name = "Weapon_P19.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/p19/p90_clipin.mp3" } )
sound.Add( { name = "Weapon_P19.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/p19/p90_boltpull.mp3" } )
--p90
sound.Add( { name = "P90_weapon.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/p90_smg/p90-1.wav" } )
sound.Add( { name = "P90_weapon.unlock", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/p90_smg/p90_unlock.mp3" } )
sound.Add( { name = "P90_weapon.magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/p90_smg/p90_magout.mp3" } )
sound.Add( { name = "P90_weapon.magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/p90_smg/p90_magin.mp3" } )
sound.Add( { name = "P90_weapon.cock", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/p90_smg/p90_cock.mp3" } )
--sten
sound.Add( { name = "Weaponsten.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/sten/mp5-1.wav" } )
sound.Add( { name = "Weaponsten.clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/sten/mp5_clipout.mp3" } )
sound.Add( { name = "Weaponsten.clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/sten/mp5_clipin.mp3" } )
sound.Add( { name = "Weaponsten.boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/sten/mp5_boltpull.mp3" } )
sound.Add( { name = "Weaponsten.boltslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/sten/mp5_boltslap.mp3" } )
sound.Add( { name = "Weapon_stengun.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/sten/mp5_slideback.mp3" } )
--tommygun
sound.Add( { name = "Weapon_tmg.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/tmg/tmg_1.wav" } )
sound.Add( { name = "Weapon_tmg.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tmg/tmg_magout.mp3" } )
sound.Add( { name = "Weapon_tmg.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tmg/tmg_magin.mp3" } )
sound.Add( { name = "Weapon_tmg.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/tmg/tmg_cock.mp3" } )
--MP7
sound.Add( { name = "Weapon_MP7.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/mp7/usp1.wav" } )
sound.Add( { name = "Weapon_MP7.magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp7/mp7_magout.mp3" } )
sound.Add( { name = "Weapon_MP7.magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp7/mp7_magin.mp3" } )
sound.Add( { name = "Weapon_MP7.charger", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/mp7/mp7_charger.mp3" } )
--uzi
sound.Add( { name = "Weapon_uzi.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/uzi/mac10-1.wav" } )
sound.Add( { name = "imi_uzi_09mm.boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/uzi/mac10_boltpull.mp3" } )
sound.Add( { name = "imi_uzi_09mm.clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/uzi/mac10_clipin.mp3" } )
sound.Add( { name = "imi_uzi_09mm.clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/uzi/mac10_clipout.mp3" } )
--MP5SD
sound.Add( { name = "Weapon_hkmp5sd.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/hkmp5sd/mp5-1.wav" } )
sound.Add( { name = "Weapon_hkmp5sd.magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hkmp5sd/magout.mp3" } )
sound.Add( { name = "Weapon_hkmp5sd.magfiddle", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hkmp5sd/magfiddle.mp3" } )
sound.Add( { name = "Weapon_hkmp5sd.magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hkmp5sd/magin.mp3" } )
sound.Add( { name = "Weapon_hkmp5sd.boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hkmp5sd/boltpull.mp3" } )
sound.Add( { name = "Weapon_hkmp5sd.boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hkmp5sd/boltrelease.mp3" } )
sound.Add( { name = "Weapon_hkmp5sd.cloth", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hkmp5sd/cloth.mp3" } )
sound.Add( { name = "Weapon_hkmp5sd.safety", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hkmp5sd/safety.mp3" } )
--HoneyBadger
sound.Add( { name = "Weapon_HoneyB.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/hb/hb_fire.wav" } )
sound.Add( { name = "Weapon_HoneyB.Magout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hb/magout.mp3" } )
sound.Add( { name = "Weapon_HoneyB.Magin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hb/magin.mp3" } )
sound.Add( { name = "Weapon_HoneyB.Boltcatch", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hb/boltcatch.mp3" } )
sound.Add( { name = "Weapon_HoneyB.Boltforward", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hb/boltforward.mp3" } )
sound.Add( { name = "Weapon_HoneyB.Boltback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/hb/boltback.mp3" } )
--coltpython
sound.Add( { name = "Weapon_ColtPython.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/coltpython/python-1.wav" } )
sound.Add( { name = "WepColtPython.clipdraw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/coltpython/clipdraw.mp3" } )
sound.Add( { name = "WepColtPython.blick", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/coltpython/blick.mp3" } )
sound.Add( { name = "WepColtPython.bulletsout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/coltpython/bulletsout.mp3" } )
sound.Add( { name = "WepColtPython.bulletsin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/coltpython/bulletsin.mp3" } )
--RagingBull
sound.Add( { name = "weapon_r_bull.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/r_bull/r-bull-1.wav" } )
sound.Add( { name = "weapons_r_bull_bullreload_wav", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/r_bull/bullreload.mp3" } )
sound.Add( { name = "weapons_r_bull_draw_gun_wav", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/r_bull/draw_gun.mp3" } )
--smithandwessonmodel3
sound.Add( { name = "Model3.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/model3/model3-1.wav" } )
sound.Add( { name = "Model3.Hammer", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model3/Hammer.mp3" } )
sound.Add( { name = "Model3.Break_Eject", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model3/Break_eject.mp3" } )
sound.Add( { name = "Model3.bulletout_1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model3/bulletout_1.mp3" } )
sound.Add( { name = "Model3.bulletout_2", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model3/bulletout_2.mp3" } )
sound.Add( { name = "Model3.bulletout_3", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model3/bulletout_3.mp3" } )
sound.Add( { name = "Model3.bullets_in", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model3/bullets_in.mp3" } )
sound.Add( { name = "Model3.Break_close", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model3/Break_CLose.mp3" } )
--m29satan
sound.Add( { name = "Weapon_satan1.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/satan1/satan-1.wav" } )
sound.Add( { name = "Weapon_satan1.blick", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/satan1/blick.mp3" } )
sound.Add( { name = "Weapon_satan1.unfold", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/satan1/unfold.mp3" } )
sound.Add( { name = "Weapon_satan1.bulletsin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/satan1/bulletsin.mp3" } )
sound.Add( { name = "Weapon_satan1.bulletsout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/satan1/bulletsout.mp3" } )
--Remington1858
sound.Add( { name = "Remington.single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/remington/remington-1.wav" } )
sound.Add( { name = "Remington.cylinderhit", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/remington/cylinderhit.mp3" } )
sound.Add( { name = "Remington.cylinderswap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/remington/cylinderswap.mp3" } )
sound.Add( { name = "Remington.bounce1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/remington/bounce1.mp3" } )
sound.Add( { name = "Remington.bounce1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/remington/bounce2.mp3" } )
sound.Add( { name = "Remington.bounce1", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/remington/bounce3.mp3" } )
sound.Add( { name = "Remington.Hammer", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/remington/hammer.mp3" } )
--BERETTAM92
sound.Add( { name = "Weapon_m92b.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = ")weapons/beretta92/berettam92-1.wav" } )
sound.Add( { name = "Weapon_beretta92.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/beretta92/berettam92_clipout.mp3" } )
sound.Add( { name = "Weapon_beretta92.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/beretta92/berettam92_clipin.mp3" } )
sound.Add( { name = "Weapon_beretta92.Sliderelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/beretta92/berettam92_sliderelease.mp3" } )
sound.Add( { name = "Weapon_beretta92.Slidepull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/beretta92/berettam92_slidepull.mp3" } )
sound.Add( { name = "Weapon_beretta92.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/beretta92/berettam92_slideback.mp3" } )
--hk45c
sound.Add( { name = "Weapon_hk45.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/hk45/hk45-1.wav" } )
sound.Add( { name = "HK45C.Deploy", channel = CHAN_ITEM, volume = 1, sound = "weapons/hk45/draw.mp3" } )
sound.Add( { name = "HK45C.Magout", channel = CHAN_ITEM, volume = 1, sound = "weapons/hk45/magout.mp3" } )
sound.Add( { name = "HK45C.Magin", channel = CHAN_ITEM, volume = 1, sound = "weapons/hk45/magin.mp3" } )
sound.Add( { name = "HK45C.Release", channel = CHAN_ITEM, volume = 1, sound = "weapons/hk45/sliderelease.mp3" } )
sound.Add( { name = "HK45C.Slidepull", channel = CHAN_ITEM, volume = 1, sound = "weapons/hk45/slidepull.mp3" } )
--usp
sound.Add( { name = "Weapon_fokkususp.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/fokku_tc_usp/fiveseven-1.wav" } )
sound.Add( { name = "Weapon_fokkususp.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_usp/fiveseven_clipout.mp3" } )
sound.Add( { name = "Weapon_fokkususp.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_usp/fiveseven_clipin.mp3" } )
sound.Add( { name = "Weapon_fokkususp.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_usp/fiveseven_slideback.mp3" } )
sound.Add( { name = "Weapon_fokkususp.Slidepull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_usp/fiveseven_slidepull.mp3" } )
--SigP228
sound.Add( { name = "Sauer1_P228.Single", channel = CHAN_USER_BASE + 10, volume = 1, sound = "weapons/sig_p228/p228-1.wav" } )
sound.Add( { name = "Sauer1_P228.Magout", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/magout.mp3" } )
sound.Add( { name = "Sauer1_P228.Magin", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/magin.mp3" } )
sound.Add( { name = "Sauer1_P228.MagShove", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/magshove.mp3" } )
sound.Add( { name = "Sauer1_P228.Sliderelease", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/sliderelease.mp3" } )
sound.Add( { name = "Sauer1_P228.Cloth", channel = CHAN_ITEM, volume = .5, sound = "weapons/sig_p228/cloth.mp3" } )
sound.Add( { name = "Sauer1_P228.Shift", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/shift.mp3" } )
--glock18
sound.Add( { name = "Dmgfok_glock.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dmg_glock/mac10-1.wav" } )
sound.Add( { name = "Dmgfok_glock.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_glock/magout.mp3" } )
sound.Add( { name = "Dmgfok_glock.clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_glock/magin.mp3" } )
sound.Add( { name = "Dmgfok_glock.Boltpull", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_glock/boltpull.mp3" } )
sound.Add( { name = "Dmgfok_glock.Boltrelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_glock/boltrelease.mp3" } )
sound.Add( { name = "Dmgfok_glock.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_glock/mac10_deploy.mp3" } )
--colt1911
sound.Add( { name = "Dmgfok_co1911.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/dmg_colt1911/deagle-1.wav" } )
sound.Add( { name = "Dmgfok_co1911.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_colt1911/draw.mp3" } )
sound.Add( { name = "Dmgfok_co1911.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_colt1911/de_clipin.mp3" } )
sound.Add( { name = "Dmgfok_co1911.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_colt1911/de_slideback.mp3" } )
sound.Add( { name = "Dmgfok_co1911.Draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/dmg_colt1911/draw.mp3" } )
--luger
sound.Add( { name = "Weapon_luger.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/luger/luger-1.wav" } )
sound.Add( { name = "Weapon_luger.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/luger/luger_clipout.mp3" } )
sound.Add( { name = "Weapon_luger.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/luger/luger_clipin.mp3" } )
sound.Add( { name = "Weapon_luger.Sliderelease", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/luger/luger_sliderelease.mp3" } )
--deserteagle
sound.Add( { name = "Weapon_TDegle.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/fokku_tc_deagle/deagle-1.wav" } )
sound.Add( { name = "Weapon_TDegle.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_deagle/de_clipout.mp3" } )
sound.Add( { name = "Weapon_TDegle.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_deagle/de_clipin.mp3" } )
sound.Add( { name = "Weapon_TDegle.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_deagle/de_slideback.mp3" } )
sound.Add( { name = "Weapon_TDegle.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/fokku_tc_deagle/de_deploy.mp3" } )
--SigP229R
sound.Add( { name = "Sauer1_P228.Single", channel = CHAN_USER_BASE + 10, volume = 1, sound = "weapons/sig_p228/p228-1.wav" } )
sound.Add( { name = "Sauer1_P228.Magout", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/magout.mp3" } )
sound.Add( { name = "Sauer1_P228.Magin", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/magin.mp3" } )
sound.Add( { name = "Sauer1_P228.MagShove", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/magshove.mp3" } )
sound.Add( { name = "Sauer1_P228.Sliderelease", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/sliderelease.mp3" } )
sound.Add( { name = "Sauer1_P228.Cloth", channel = CHAN_ITEM, volume = .5, sound = "weapons/sig_p228/cloth.mp3" } )
sound.Add( { name = "Sauer1_P228.Shift", channel = CHAN_ITEM, volume = 1, sound = "weapons/sig_p228/shift.mp3" } )
--Model500
sound.Add( { name = "Model_500.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/model500/deagle-1.wav" } )
sound.Add( { name = "saw_model_500.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model500/de_clipin.mp3" } )
sound.Add( { name = "saw_model_500.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model500/de_clipout.mp3" } )
sound.Add( { name = "saw_model_500.Deploy", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model500/de_deploy.mp3" } )
sound.Add( { name = "saw_model_500.Slideback", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/model500/de_slideback.mp3" } )
--S&W627
sound.Add( { name = "model_627perf.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/627/deagle-1.wav" } )
sound.Add( { name = "model_627perf.wheel_in", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/627/wheel_in.mp3" } )
sound.Add( { name = "model_627perf.bullets_in", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/627/bullets_in.mp3" } )
sound.Add( { name = "model_627perf.bulletout_3", channel = CHAN_USER_BASE + 11, volume = 1.0, sound = "weapons/627/bulletout_3.mp3" } )
sound.Add( { name = "model_627perf.bulletout_2", channel = CHAN_USER_BASE + 12, volume = 1.0, sound = "weapons/627/bulletout_2.mp3" } )
sound.Add( { name = "model_627perf.bulletout_1", channel = CHAN_USER_BASE + 13, volume = 1.0, sound = "weapons/627/bulletout_1.mp3" } )
sound.Add( { name = "model_627perf.wheel_out", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/627/wheel_out.mp3" } )
--usc
sound.Add( { name = "Weapon_hkusc.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = { "weapons/usc/ump45-1.wav", "weapons/usc/ump45-2.wav" } } )
sound.Add( { name = "Weapon_hkusc.Clipout", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/usc/ump45_clipout.mp3" } )
sound.Add( { name = "Weapon_hkusc.Clipin", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/usc/ump45_clipin.mp3" } )
sound.Add( { name = "Weapon_hkusc.Boltslap", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/usc/ump45_boltslap.mp3" } )

--EX41
sound.Add( { name = "EX41.Pump", channel = CHAN_ITEM, volume = 1, sound = "weapons/ex41/m3_pump.mp3" } )
sound.Add( { name = "EX41.Insertshell", channel = CHAN_ITEM, volume = 1, sound = "weapons/ex41/m3_insertshell.mp3" } )
sound.Add( { name = "EX41.Draw", channel = CHAN_ITEM, volume = 1, sound = "weapons/ex41/draw.mp3" } )

--RPG
sound.Add( { name = "RPGF.single", channel = CHAN_USER_BASE + 10, volume = 1.0, soundlevel = 155, sound = "GDC/Rockets/RPGF.wav" } )
sound.Add( { name = "M202F.single", channel = CHAN_USER_BASE + 10, volume = 1.0, soundlevel = 155, sound = { "GDC/Rockets/M202F.wav", "gdc/rockets/m202f2.wav" } } )
sound.Add( { name = "MATADORF.single", channel = CHAN_USER_BASE + 10, volume = 1.0, soundlevel = 155, sound = "GDC/Rockets/MATADORF.wav" } )

--Suicide bomb
sound.Add( { name = "sb.click", channel = CHAN_USER_BASE + 10, volume = "1", sound = "weapons/suicidebomb/c4_click.mp3" } )

-- m79 grenade launcher
sound.Add( { name = "M79_launcher.close", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M79/m79_close.mp3" } )
sound.Add( { name = "M79_glauncher.barrelup", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M79/barrelup.mp3" } )
sound.Add( { name = "M79_glauncher.InsertShell", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M79/xm_insert.mp3" } )
sound.Add( { name = "M79_launcher.draw", channel = CHAN_ITEM, volume = 1.0, sound = "weapons/M79/m79_close.mp3" } )
sound.Add( { name = "40mmGrenade.Single", channel = CHAN_USER_BASE + 10, volume = 1.0, sound = "weapons/M79/40mmthump.wav" } )
