game.AddAmmoType( { name = "SatCannon", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "40mmGrenade", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "C4Explosive", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "ProxMine", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "Improvised_Explosive", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "Nuclear_Warhead", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "NerveGas", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "StickyGrenade", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "Harpoon", dmgtype = DMG_BULLET } )
game.AddAmmoType( { name = "nitroG", dmgtype = DMG_BULLET } )

game.AddParticles( "particles/nitro_main.pcf" )
